// Copyright 2025 Sylos contributors
// SPDX-License-Identifier: LGPL-2.1-or-later

package queue

import (
	"fmt"

	"codeberg.org/Sylos/Migration-Engine/pkg/db"
	"codeberg.org/Sylos/Migration-Engine/pkg/logservice"
	"codeberg.org/Sylos/Sylos-FS/pkg/types"
)

// SeedRootTask inserts the initial root folder task into DuckDB to kickstart traversal.
// For src: sets traversal_status='Pending' and copy_status='Successful' (root is not a copy task).
// For dst: sets traversal_status='Pending'
// Ensures stats bucket exists and is updated with root task counts.
// rootNodeID should be db.RootNodeID(queueType).
func SeedRootTask(queueType string, rootFolder types.Folder, rootNodeID string, database *db.DB) error {
	if database == nil {
		return fmt.Errorf("database cannot be nil")
	}

	if rootNodeID == "" {
		return fmt.Errorf("rootNodeID cannot be empty - must be generated by db.RootNodeID()")
	}

	_, _, ok := db.GetRootNode(database, queueType)
	if ok {
		// Root already exists.
		return nil
	}

	// Create NodeState from root folder
	// Root is always at "/" (normalized), regardless of actual folder path.
	// Queue node Type is structural (folder|file); cloud tags like team_folder stay on the FS root only.
	state := &db.NodeState{
		ID:              rootNodeID,           // Deterministic ID for database keys
		ServiceID:       rootFolder.ServiceID, // FS identifier
		ParentID:        "",                   // Root has no parent
		ParentServiceID: rootFolder.ParentId,  // Parent's FS identifier (may be empty for root)
		ParentPath:      "",                   // Root has no parent
		Name:            rootFolder.DisplayName,
		Path:            "/", // Root is always "/" (normalized), regardless of actual folder path
		Type:            types.NodeTypeFolder,
		Size:            0, // Folders have no size
		MTime:           rootFolder.LastUpdated,
		Depth:           0, // Root is always depth 0
		Status:          db.StatusPending,
	}

	// Populate traversal status in the NodeState metadata
	state.TraversalStatus = db.StatusPending
	if queueType == "SRC" {
		// The SRC root is never a copy task; it already exists on both sides for migration purposes.
		state.CopyStatus = db.CopyStatusAlreadyExisted
	}

	if err := db.InsertRootNode(database, queueType, state); err != nil {
		return fmt.Errorf("failed to seed root task for %s: %w", queueType, err)
	}

	if logservice.LS != nil {
		err := logservice.LS.Log(
			"info",
			fmt.Sprintf("Seeded root task: %s (path: %s)", rootFolder.DisplayName, rootFolder.LocationPath),
			"seeding",
			queueType,
		)
		if err != nil {
			fmt.Println("error logging", err)
		}
	}

	return nil
}

// SeedRootTasks is a convenience function to seed both src and dst root tasks at once.
// Writes root tasks to DuckDB.
// Generates deterministic IDs for both root nodes and matches DST root to SRC root.
func SeedRootTasks(srcRoot types.Folder, dstRoot types.Folder, database *db.DB) error {
	_, _, srcOk := db.GetRootNode(database, "SRC")
	_, _, dstOk := db.GetRootNode(database, "DST")
	if srcOk && dstOk {
		return nil
	}

	srcRootID := db.RootNodeID("SRC")
	dstRootID := db.RootNodeID("DST")

	// Seed SRC root first
	if err := SeedRootTask("SRC", srcRoot, srcRootID, database); err != nil {
		return fmt.Errorf("failed to seed src root: %w", err)
	}

	// Seed DST root with SrcID pointing to SRC root
	// This ensures root nodes are matched from the start
	if err := SeedRootTaskWithSrcID("DST", dstRoot, dstRootID, srcRootID, database); err != nil {
		return fmt.Errorf("failed to seed dst root: %w", err)
	}

	// Append-only id_map for root so DST depth-0 pulls can resolve SRC children via parent_id.
	database.AppendIDMapEvent(db.IDMapEvent{
		SrcInternalID: srcRootID,
		DstInternalID: dstRootID,
		Source:        db.IDMapSourceRootSeed,
		Status:        db.IDMapStatusActive,
	})

	err := database.Checkpoint()
	if err != nil {
		fmt.Println("error checkpointing", err)
	}

	if logservice.LS != nil {
		err := logservice.LS.Log(
			"info",
			"Successfully seeded both src and dst root tasks",
			"seeding",
			"main",
		)
		if err != nil {
			fmt.Println("error logging", err)
		}
	}

	return nil
}

// SeedRootTaskWithSrcID inserts the initial root folder task into DuckDB with a pre-set SrcID.
// This is used for DST root nodes that need to be matched to SRC root nodes.
// rootNodeID should be db.RootNodeID(queueType).
func SeedRootTaskWithSrcID(queueType string, rootFolder types.Folder, rootNodeID string, srcID string, database *db.DB) error {
	if database == nil {
		return fmt.Errorf("database cannot be nil")
	}

	if rootNodeID == "" {
		return fmt.Errorf("rootNodeID cannot be empty - must be generated by db.RootNodeID()")
	}

	if queueType != "DST" {
		return fmt.Errorf("SeedRootTaskWithSrcID should only be used for DST queue type")
	}

	_, _, ok := db.GetRootNode(database, queueType)
	if ok {
		return nil
	}

	// Create NodeState from root folder (path is join key; SrcID is for join only, not stored in node table).
	// Queue node Type is structural (folder|file); cloud tags like team_folder stay on the FS root only.
	state := &db.NodeState{
		ID:              rootNodeID,           // Deterministic ID for database keys
		ServiceID:       rootFolder.ServiceID, // FS identifier
		ParentID:        "",                   // Root has no parent
		ParentServiceID: rootFolder.ParentId,  // Parent's FS identifier (may be empty for root)
		ParentPath:      "",                   // Root has no parent
		Name:            rootFolder.DisplayName,
		Path:            "/", // Root is always "/" (normalized)
		Type:            types.NodeTypeFolder,
		Size:            0, // Folders have no size
		MTime:           rootFolder.LastUpdated,
		Depth:           0, // Root is always depth 0
		Status:          db.StatusPending,
		SrcID:           srcID, // For join; not persisted in node row
	}

	// Populate traversal status in the NodeState metadata
	state.TraversalStatus = db.StatusPending

	// Use direct single-row insert (same as SRC root) for immediate turnaround.
	if err := db.InsertRootNode(database, queueType, state); err != nil {
		return fmt.Errorf("failed to seed root task for %s: %w", queueType, err)
	}

	if logservice.LS != nil {
		err := logservice.LS.Log(
			"info",
			fmt.Sprintf("Seeded root task: %s (path: %s, src_id: %s)", rootFolder.DisplayName, rootFolder.LocationPath, srcID),
			"seeding",
			queueType,
		)
		if err != nil {
			fmt.Println("error logging", err)
		}
	}

	return nil
}
