run:
  timeout: 5m
  tests: false

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - unused
    - gosimple
    - errcheck
    - bodyclose
    - contextcheck
    - errorlint
    - gocritic
    - gosec
    - revive
    - prealloc
    - exportloopref

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  revive:
    rules:
      - name: var-naming
      - name: indent-error-flow
      - name: empty-lines
      - name: superfluous-else

issues:
  exclude-use-default: false
